#!/bin/bash

if [ -f "/etc/iptables.rules" ]; then
    mv --backup=t /etc/iptables.rules{,.save}
fi

iptables-save > /etc/iptables.rules
mv --backup=t /etc/iptables.rules{,.save}

cat > /etc/iptables.rules<<-EOF
# Generated by xtables-save v1.8.2 on Sat Feb 20 21:54:32 2021
*nat
:PREROUTING ACCEPT [281:17383]
:INPUT ACCEPT [276:17053]
:POSTROUTING ACCEPT [708:105067]
:OUTPUT ACCEPT [2149:224061]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 172.30.32.0/23 ! -o hassio -j MASQUERADE
-A POSTROUTING -s 172.30.32.6/32 -d 172.30.32.6/32 -p tcp -m tcp --dport 80 -j MASQUERADE
-A POSTROUTING -s 10.0.0.0/8 -o eth0 -j SNAT --to-source 192.168.18.182
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A DOCKER -i docker0 -j RETURN
-A DOCKER -i hassio -j RETURN
-A DOCKER ! -i hassio -p tcp -m tcp --dport 4357 -j DNAT --to-destination 172.30.32.6:80
COMMIT
# Completed on Sat Feb 20 21:54:32 2021
# Generated by xtables-save v1.8.2 on Sat Feb 20 21:54:32 2021
*filter
:INPUT ACCEPT [2757291:267537017]
:FORWARD ACCEPT [191:63962]
:OUTPUT ACCEPT [2718102:263652591]
:DOCKER - [0:0]
:DOCKER-ISOLATION-STAGE-1 - [0:0]
:DOCKER-ISOLATION-STAGE-2 - [0:0]
:DOCKER-USER - [0:0]
-A INPUT -i eth0 -p esp -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --dport 500 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --dport 4500 -j ACCEPT
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o hassio -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o hassio -j DOCKER
-A FORWARD -i hassio ! -o hassio -j ACCEPT
-A FORWARD -i hassio -o hassio -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.0.0.0/8 -j ACCEPT
-A DOCKER -d 172.30.32.6/32 ! -i hassio -o hassio -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i hassio ! -o hassio -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o hassio -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
COMMIT
# Completed on Sat Feb 20 21:54:32 2021
# Generated by xtables-save v1.8.2 on Sat Feb 20 21:54:32 2021
*mangle
:PREROUTING ACCEPT [72071:72993608]
:INPUT ACCEPT [2757288:267536831]
:FORWARD ACCEPT [294:71500]
:OUTPUT ACCEPT [2718100:263652445]
:POSTROUTING ACCEPT [2724722:264266572]
:V2RAY - [0:0]
:V2RAY_MASK - [0:0]
-A PREROUTING -j V2RAY
-A OUTPUT -j V2RAY_MASK
-A V2RAY -d 127.0.0.0/8 -j RETURN
-A V2RAY -d 224.0.0.0/4 -j RETURN
-A V2RAY -d 255.255.255.255/32 -j RETURN
#-A V2RAY -d 192.168.0.0/16 -p tcp -j RETURN
#-A V2RAY -d 192.168.0.0/16 -p udp -m udp ! --dport 53 -j RETURN
-A V2RAY -d 192.168.0.0/16 -j RETURN
#-A V2RAY -d 172.16.0.0/12 -j RETURN
#-A V2RAY -s 172.16.0.0/12 -j RETURN
-A V2RAY -i docker0 -j RETURN
-A V2RAY -o docker0 -j RETURN
-A V2RAY -i hassio -j RETURN
-A V2RAY -o hassio -j RETURN
-A V2RAY -d 10.0.0.0/8 -j RETURN
#-A V2RAY -s 10.0.0.0/8 -j RETURN
#-A V2RAY -s 172.16.0.0/12 -p udp -m udp --dport 53 -j RETURN
#-A V2RAY -s 172.16.0.0/12 -p tcp -m tcp --dport 853 -j RETURN
#-A V2RAY -s 172.16.0.0/12 -p tcp -m tcp --dport 80 -j RETURN
#-A V2RAY -s 172.16.0.0/12 -p tcp -m tcp --dport 443 -j RETURN
-A V2RAY -p udp -j TPROXY --on-port 12345 --on-ip 0.0.0.0 --tproxy-mark 0x1/0xffffffff
-A V2RAY -p tcp -j TPROXY --on-port 12345 --on-ip 0.0.0.0 --tproxy-mark 0x1/0xffffffff
#-A V2RAY_MASK -d 127.0.0.0/8 -j RETURN
-A V2RAY_MASK -d 224.0.0.0/4 -j RETURN
-A V2RAY_MASK -d 255.255.255.255/32 -j RETURN
#-A V2RAY_MASK -d 192.168.0.0/16 -p tcp -j RETURN
#-A V2RAY_MASK -d 192.168.0.0/16 -p udp -m udp ! --dport 53 -j RETURN
-A V2RAY_MASK -d 192.168.0.0/16 -j RETURN
#-A V2RAY_MASK -d 172.16.0.0/12 -j RETURN
#-A V2RAY_MASK -s 172.16.0.0/12 -j RETURN
-A V2RAY_MASK -i docker0 -j RETURN
-A V2RAY_MASK -o docker0 -j RETURN
-A V2RAY_MASK -i hassio -j RETURN
-A V2RAY_MASK -o hassio -j RETURN
-A V2RAY_MASK -d 10.0.0.0/8 -j RETURN
#-A V2RAY_MASK -s 10.0.0.0/8 -j RETURN
-A V2RAY_MASK -m mark --mark 0xff -j RETURN
-A V2RAY_MASK -p udp -j MARK --set-xmark 0x1/0xffffffff
-A V2RAY_MASK -p tcp -j MARK --set-xmark 0x1/0xffffffff
COMMIT
# Completed on Sat Feb 20 21:54:32 2021
EOF

iptables-restore < /etc/iptables.rules

cat > /etc/network/if-up.d/iptables<<-EOF
#!/bin/sh
iptables-restore < /etc/iptables.rules
EOF
